language: ruby
cache:
  bundler: true
rvm:
- 2.0.0-p451
branches:
  only:
  - master
bundler_args: --without development --path=~/.bundle
before_install:
- 'echo ''gem: --no-ri --no-rdoc'' > ~/.gemrc'
- gem install bundler
- bundle config build.nokogiri --use-system-libraries
- gem install nokogiri -- --use-system-libraries
- gem install bundle_cache
- bundle_cache_install
before_script:
- eval `ssh-agent -s`
- openssl aes-256-cbc -K $encrypted_3dcb9409b0da_key -iv $encrypted_3dcb9409b0da_iv
  -in coletownsend_rsa.enc -out coletownsend_rsa -d
- echo -e "Host 69.89.16.246\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- chmod 600 coletownsend_rsa
- ssh-add coletownsend_rsa
script:
- bundle exec rake deploy
after_script:
- bundle_cache
env:
  global:
  - BUNDLE_ARCHIVE="bundle-archive"
  - AWS_S3_BUCKET="coletownsend-bundler-cache"
  - secure: bQKML3wZj5Nau261zxRzYdLZhZ+YT8LVYrIWF1VGk2xEe+84g29Eufb2LNUDErIVcsJ2p5Tc5ipOiPnRfDyitd+Ca4o8X+K8OWh3BHG6Fq+Y7uvMmqaaIiiMLhjOtBqXTJxhJtEr6fo6fvVMjs5nnOvRCJZvjp7Idopl2ZISyWM=
  - secure: egXy9onIifS2ojpmW3jnIdR4mdzoaeOMKc6wLqBy7OB9I/oflR33AK5miemtinL8o/KEDl3pmpXM3RqF1VqvIGgrsWlTpWBz+iLm+1aaAza6F/L86HzG0qMOkBvtH9zuBHjb9CEAZP2wPN8Uz3pvcLfh5qLlwjYoCyQCrngN040=
