language: ruby
cache:
  bundler: true
rvm:
- 2.0.0-p451
branches:
  only:
  - master
bundler_args: --without development --path=~/.bundle
before_install:
- 'echo ''gem: --no-ri --no-rdoc'' > ~/.gemrc'
- gem install bundler
- bundle config build.nokogiri --use-system-libraries
- gem install nokogiri -- --use-system-libraries
- gem install bundle_cache
- bundle_cache_install
before_script:
- echo -e "Host 69.89.16.246\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- chmod 600 coletowndend_rsa
- ssh-add coletowndend_rsa
script:
- git config --global user.email "cole@coletownsend.com"
- git config --global user.name "Cole Townsend"
- bundle exec rake deploy
after_script:
- bundle_cache
env:
  global:
  - BUNDLE_ARCHIVE="bundle-archive"
  - AWS_S3_BUCKET="coletownsend-bundler-cache"
  - secure: bQKML3wZj5Nau261zxRzYdLZhZ+YT8LVYrIWF1VGk2xEe+84g29Eufb2LNUDErIVcsJ2p5Tc5ipOiPnRfDyitd+Ca4o8X+K8OWh3BHG6Fq+Y7uvMmqaaIiiMLhjOtBqXTJxhJtEr6fo6fvVMjs5nnOvRCJZvjp7Idopl2ZISyWM=
